# Problem set 0: Getting started

**Learning goals**: Revisit the core ideas from Lectures 2-3.

- Atomic types, containers and **references** (a slice of a list is a copy, a slice of a numpy array is a **view**)
- Conditionals and loops (`break`, `continue`, list comprehensions, `zip`)
- Functions and **scope** (global vs. local variables)
- Floating point numbers (never compare floats with `==`)
- `numpy` (views/copies and broadcasting)
- Classes (attributes, methods, `__init__`, `__str__`)

**Note:** This notebook repeats **Task 2** and **Task 4** from `Problem_set_0_Getting_started.pdf`.

Answers to Task 4 are in the `A*.py` files.

## Task 2: Understanding code

For each snippet below, **first write down your expected output on paper**. Then run the cell and check whether you were correct.

**indexing and references**

In [1]:
x = [1,2,3]
y = x
y[-1] = 4
print(x)

[1, 2, 4]


**slicing**

In [2]:
x = [0,1,2,3,4,5]
print(x[:2])
print(x[2:])

[0, 1]
[2, 3, 4, 5]


**loops - break**

In [3]:
for i in range(5):
    if i >= 2: break
    print(i)

0
1


**loops - continue**

In [4]:
for i in range(5):
    if i == 2: continue
    print(i)

0
1
3
4


**conditionals**

In [5]:
x = 3
if x > 3:
    print('too big')
elif x < 1:
    print('too small')
else:
    print('just right')

just right


**functions and scope**

In [6]:
a = 1
def f(x):
    return x+a # a is global variable
def g(x,a=1):
    return x+a # a is local variable
print(f(1))
print(g(1))
a = 2
print(f(1))
print(g(1))

2
2
3
2


**dictionaries**

In [7]:
d = {'a': 1, 'b': 2}
for key in d:
    d[key] = d[key]*2
print(d['a'] + d['b'])
print('c' in d)

6
False


**list comprehension and zip**

In [8]:
a = [1,2,3]
b = [4,5,6]
c = [i+j for i,j in zip(a,b)]
print(c)

[5, 7, 9]


**floating point numbers**

In [9]:
print(0.1 + 0.2 == 0.3)
import math
print(math.isclose(0.1 + 0.2, 0.3))

False
True


**classes**

In [10]:
class SquareClass:
    def __init__(self,length,width):
        self.length = length
        self.width = width
    def size(self):
        return self.length*self.width
square = SquareClass(2,2)
print(square.size())

4


**numpy - view and copies I**

In [11]:
import numpy as np
x = np.array([1,2,3])
y = x
x += 1
print(y)
x[:] = x + 1
print(y)
x = x + 1
print(y)

[2 3 4]
[3 4 5]
[3 4 5]


**numpy - view and copies II**

In [12]:
import numpy as np
A = np.array([0,1,2,3,4])
B = A[1:4]
B[:] = 0
print(A)

[0 0 0 0 4]


**numpy - broadcasting**

In [13]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
print(A + b)

[[11 22 33]
 [14 25 36]]


## Task 4: Putting it together

Write your own code to solve each task. The answers are in the `A*.py` files.

**1. Grid search (numpy):** Create a numpy array `x` of 100 evenly spaced points
between 0.01 and 10 (use `np.linspace`). Let utility be $u(x)=\sqrt{x}$. Without writing
a loop, find and print the value of `x` for which $u(x)$ is closest to 2.
Hint: combine `np.abs` and `np.argmin`.

In [14]:
# write your own code here

**Answer:**

In [15]:
from A1 import grid_search
x_best = grid_search()

x = 4.0464 gives u(x) = 2.0116 (closest to 2)


**2. Broadcasting (numpy):** Let `p = np.array([1,2,5])` be prices and
`q = np.array([10,20,30,40])` be quantities. Without any loop, construct the $4\times3$
matrix `E` where `E[i,j] = q[i]*p[j]`. Print `E` and `E.shape`.
Hint: use `None` to add a new axis, e.g. `q[:,None]`.

In [16]:
# write your own code here

**Answer:**

In [17]:
from A2 import expenditure_matrix
E = expenditure_matrix()

[[ 10  20  50]
 [ 20  40 100]
 [ 30  60 150]
 [ 40  80 200]]
shape: (4, 3)


**3. A class:** Write a class `ConsumerClass` that stores income `I` and prices
`p1`, `p2` as attributes (set in `__init__` with sensible defaults that can be overridden).
Add a method `demand(alpha)` that returns the Cobb-Douglas demands
$(x_1,x_2)=(\alpha I/p_1,(1-\alpha)I/p_2)$ as a tuple, and a `__str__` method that returns
a readable summary. Create two consumers with different incomes and print their demands
for $\alpha=0.5$.

In [18]:
# write your own code here

**Answer:**

In [19]:
from A3 import solve
solve()

ConsumerClass(I=10.0, p1=1.0, p2=2.0) -> demand(0.5) = (5.00, 2.50)
ConsumerClass(I=20.0, p1=1.0, p2=2.0) -> demand(0.5) = (10.00, 5.00)
